services:
  backend:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - .:/app:Z
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["go", "run", "cmd/server/main.go"]
